name: install-emscripten
description: "Install Emscripten from source"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: emscripten-core/emsdk
        path: emsdk
    - run: ./emsdk/emsdk install latest
      shell: bash
    - run: ./emsdk/emsdk activate latest --permanent
      shell: bash
    - run: echo `readlink -f ./emsdk/upstream/emscripten` >> $GITHUB_PATH
      shell: bash
    - run: emcc -v
      shell: bash
