c_compiler = ["clang"]
cpp_compiler = ["clang++"]
static_linker = ["llvm-ar", "qc"]
exe_linker = ["clang++"]

[profile.Debug]
c_compile_flags = ["-g", "-Xclang", "-gcodeview", "-O0", "-D_DEBUG", "-Xclang", "--dependent-lib=libcmtd"]
cpp_compile_flags = ["-g", "-Xclang", "-gcodeview", "-O0", "-D_DEBUG", "-Xclang", "--dependent-lib=libcmtd"]

[profile.Release]
c_compile_flags = ["-O3", "-DNDEBUG"]
cpp_compile_flags = ["-O3", "-DNDEBUG"]
