c_compiler = ["clang"]
cpp_compiler = ["clang++"]
nasm_assembler = ["nasm", "-felf64"]
static_linker = ["llvm-ar", "qc"]
exe_linker = ["clang++"]

[profile.Debug]
c_compile_flags = ["-g", "-Xclang", "-gcodeview", "-O0", "-D_DEBUG", "-Xclang", "--dependent-lib=libcmtd"]
cpp_compile_flags = ["-g", "-Xclang", "-gcodeview", "-O0", "-D_DEBUG", "-Xclang", "--dependent-lib=libcmtd"]
nasm_assemble_flags = ["-O0", "-Xgnu"]

[profile.Release]
c_compile_flags = ["-O3", "-DNDEBUG"]
cpp_compile_flags = ["-O3", "-DNDEBUG"]
nasm_assemble_flags = ["-Ox", "-Xgnu"]
