[package]
name = "test_one"

[dependencies]
zstd = { version = "1.5.5", registry = "https://catapult.trav.bid:6400/api", channel = "travbid/main"}
mydep = { path = "submodules/my_depend", options = { build_tests = true, foo = "bar" } }

[options]
c_standard = "17"
cpp_standard = "17"
position_independent_code = true
